### ISSUE TITLE
Controls Documentation

### ISSUE THREAD

**Issue by kriziacamilleuayan** [plus1tv/react-anime#71]
Hi, sorry but I'm kinda stuck with the [controls ](https://animejs.com/documentation/#playPause)part because it's not listed on the documentation.  
I also tried to read the source code and some examples but my code wont work, It'll be great if you add it on `Read.me` for noobies like me. Thank you!

**Comment by b30wulffz** [comment]
Functions can be triggered by creating references (React.createRef()) of the <Anime> component, and then calling functions using these refs as `ref.current.anime.FUNCTION()` where FUNCTION() can be replaced by play(), pause(), restart(), etc.

To know more, do `console.log(ref.current.anime)` and see what all functions are present.

I have attached an example for your reference:

```javascript
import React from "react";
import "./styles.css";

import Anime from "react-anime";

export default function App() {
  const refer = React.createRef(); //created a reference which is used to identify a rendered component
  return (
    <div className="App">
      <Anime
        autoplay={false}
        opacity={[0, 1]}
        translateX={["100vw", 0]}
        ref={refer} //giving reference to the component
        duration={5000}
      >
        Hello
      </Anime>
      <button
        onClick={() => {
          refer.current.anime.play(); //triggering play() function
        }}
      >
        Play
      </button>
      <button
        onClick={() => {
          refer.current.anime.pause(); // triggering pause() function
        }}
      >
        Pause
      </button>
      <button
        onClick={() => {
          refer.current.anime.restart(); //triggering restart() function
        }}
      >
        Restart
      </button>
    </div>
  );
}
```

Here is a link to actual implementation of the above-mentioned code: [Click Here](https://codesandbox.io/s/heuristic-cdn-dmfr8?fontsize=14&hidenavigation=1&theme=dark)

I hope it helps! 🙂

**Comment by WebKieth** [comment]
@b30wulffz u really still white components on classes? Welcome to 2021th, this unuseful adapter - it wont push reference if i try to use reference hook 😂
Really, its better to use clean animejs plugin, then this peace of problems
