### ISSUE TITLE
Animation is run on every rerender

### ISSUE THREAD

**Issue by jantimon** [plus1tv/react-anime#73]
Clicking on a button will show the animation again although there was no markup change:

![ReactAnime](https://user-images.githubusercontent.com/4113649/77230325-b0468e80-6b93-11ea-9966-b006031fa157.gif)

```tsx
import React, { useState } from "react";
import Anime from "react-anime";

export default function App() {
  const list = [0, 1, 2, 3, 4, 5];
  const [, set] = useState();
  return (
    <Anime scale={[0, 1]}>
      {list.map(i => (
        <button key={i} onClick={() => set(i)}>
          {i}
        </button>
      ))}
    </Anime>
  );
}
```

Codesandbox: https://codesandbox.io/s/react-anime-rerender-ttfbu

**Comment by abused** [comment]
I Am also having this issue, whenever rerendering occurs (in my case selecting an item), the animation is rerun.
![4luuSG5 - Imgur](https://user-images.githubusercontent.com/10110829/79055163-c4246400-7c18-11ea-9ec1-748266f64a6a.gif)

**Comment by mihaibrana** [comment]
Same here. Too bad. I really liked the simplicity of defining animations. Anyway, until a solution is found, I switched to react-spring.

**Comment by Kyliathy** [comment]
Same here. Too bad. I really liked the simplicity of defining animations. Anyway, until a solution is found, I switched to react-spring.

**Comment by andreasonny83** [comment]
Same here

**Comment by clearink** [comment]
> 单击按钮将再次显示动画，尽管标记没有更改：
> 
> ![ReactAnime](https://user-images.githubusercontent.com/4113649/77230325-b0468e80-6b93-11ea-9966-b006031fa157.gif)
> 
> ```tsx
>  从“ react” 导入React ， {  useState  }  ; 进口动漫从“反应-动漫” ; 
>    
> 
> 出口 默认 函数 应用（） { 
>   const的 列表 =  [ 0 ， 1 ， 2 ， 3 ， 4 ， 5 ] ; 
>   const  [ ， set ]  =  useState （）; 
>   返回 （
>     < 动画 规模= { [ 0 ， 1 ] } > 
>       { 列表。映射（我 =>  （
>         <按钮 键= { i }  onClick = { （） =>  设置（i ）} > 
>           { i } 
>         < / button > 
>       ））} 
>     < / 动漫> 
>   ）; 
> }
> ```
> 
> Codesandbox：[https](https://codesandbox.io/s/react-anime-rerender-ttfbu)：//codesandbox.io/s/react-anime-rerender-ttfbu[](https://codesandbox.io/s/react-anime-rerender-ttfbu)

I think it's because the component's props have changed,Although they are both [0,1]

**Comment by Slapbox** [comment]
I haven't found any way around this, or any circumstance that I can React-Anime due to this issue. It's a beautifully simple library and I'd _really_ like to use it - but I'm not seeing how to work around this issue. I even forked the library and spent the past few hours trying to remedy this. 

@alaingalvan can you explain why this is, or what the intended use case of React-Anime is?

**Comment by BryanAM** [comment]
I second this, reach pushing functional components makes animations really hard when every update of the state triggers all animations over.

**Comment by HotPotatoC** [comment]
I also have the same problem.
