### ISSUE TITLE
Allow user to choose component to render for Anime wrapper?

### ISSUE THREAD

**Issue by Slapbox** [plus1tv/react-anime#77]
For example, using an `<li />` instead of a `<div />`. React Transition Group handles this via the `component` property. React Transition Group allows setting `null` but I assume that's impossible in this case. It would still be great to be able to render other elements though.

@alaingalvan would you be open to a PR for this?

**Comment by alaingalvan** [comment]
Yeah sure thing! 😄

Interesting, looks like [React Transition Group](https://github.com/reactjs/react-transition-group/blob/master/src/TransitionGroup.js#L14) is doing it here. Feel free to add a PR and I'll review and merge it. 😉

**Comment by alaingalvan** [comment]
Belated update, this is now in for the next release `4.1.0` and the interface matches that of React Transition Group, just set a `component` prop with what you might want (`g`, `section`, etc.) and it'll use that component type to wrap each child being animated . I'll be closing this issue, but let me know if you want to keep it open.
