### ISSUE TITLE
Cannot install react-anime

### ISSUE THREAD

**Issue by NLStom** [plus1tv/react-anime#86]
![Screen Shot 2021-03-06 at 8 50 28 AM](https://user-images.githubusercontent.com/11711430/110216000-20a7f780-7e59-11eb-9713-b96c7f6dd024.png)

**Comment by alaingalvan** [comment]
Thanks, we've been working on an update that updates React Anime to work with React 17, testing it before releasing it to NPM. In the mean time, you should still be able to install it with `--force`.

**Comment by LeonDWong** [comment]
I meet same problem when using react@18.x, could react-anime support react18?
